// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq44gANTMbS6zSMtBTeNw25ZfYtxwbI54',
    appId: '1:677643806939:web:fb327513f18788f823c4fe',
    messagingSenderId: '677643806939',
    projectId: 'task6-f554f',
    authDomain: 'task6-f554f.firebaseapp.com',
    storageBucket: 'task6-f554f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2f6Uqd8QopkgRXPY_7eidzba-81v9WoU',
    appId: '1:677643806939:android:6053f32552e9b6c023c4fe',
    messagingSenderId: '677643806939',
    projectId: 'task6-f554f',
    storageBucket: 'task6-f554f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtksvEBMToLajcH9Cd2TGadAxv5UQu5LA',
    appId: '1:677643806939:ios:bd55433809c201b223c4fe',
    messagingSenderId: '677643806939',
    projectId: 'task6-f554f',
    storageBucket: 'task6-f554f.appspot.com',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtksvEBMToLajcH9Cd2TGadAxv5UQu5LA',
    appId: '1:677643806939:ios:bd55433809c201b223c4fe',
    messagingSenderId: '677643806939',
    projectId: 'task6-f554f',
    storageBucket: 'task6-f554f.appspot.com',
    iosBundleId: 'com.example.task6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq44gANTMbS6zSMtBTeNw25ZfYtxwbI54',
    appId: '1:677643806939:web:0e54ee0a087fa61d23c4fe',
    messagingSenderId: '677643806939',
    projectId: 'task6-f554f',
    authDomain: 'task6-f554f.firebaseapp.com',
    storageBucket: 'task6-f554f.appspot.com',
  );

}